In [ ]:
import pandas as pd #imporing pandas module in the computer

In [ ]:
import matplotlib.pyplot as plt #matplotlib is a package and pyplot is a collection of functions 
#pyplot is classes -- within matplotlib library
# and gonna use uske functions

In [ ]:
import pickle

In [ ]:


# import sys
# # !{sys.executable} -m pip install pandas-profiling


In [ ]:
from pandas_profiling import ProfileReport #pands_profiling is a module importing
#ProfileReport function

In [ ]:
import numpy as np

In [ ]:
df=pd.read_csv("https://raw.githubusercontent.com/justmarkham/scikit-learn-videos/master/data/Advertising.csv")
#click raw and copy the path

In [ ]:
df

In [ ]:
df.drop(columns=["Unnamed: 0"],inplace=True) #drop is a function that we use
# columns we provide in a list - becoz we might have to drop more than two columns
# list is prvided in square bracket
#inplace = true means to updte the dataframe 

In [ ]:
df

In [ ]:
df.head() #first 5 dataset

In [ ]:
df.tail() #last 5 dataset

In [ ]:
#if i spend something on TV,Radio and newspaper - then what is the number of sale
# I'll be able to generate
#Prblm Statement : build a model that tries to predict sales when 
#tV,radio , newspaper expense is given

#which mode of advertisement is effectivee- sales
#whether this data shwing multicllinearity
#statistic or 


In [ ]:
df.describe()
#in every column we have 200 records so that means theres no null value
#avg Tv ad expense is 147 $, radio expense is 23$ and Newspaper expense is 30$
# and minimn expense that u spent n Tv is 0.70, raadio is 0
#at any pint in time - we are spending more on Tv as compared to Radio or Newspaper


In [ ]:
ProfileReport(df) #profile report jisme report banegi - usme you are passing df
# ie dataframe 

In [ ]:
pf= ProfileReport(df) #saving this report in pf

In [ ]:
pf.to_widgets()#this would give the profile in a widget formt which is more 
#interactive

In [ ]:
#how t check multicolinearity 
#if there is correlation between feature variable itself ie. called multicolinearity
# that is called multiclinearity
# x1,x2,x3 = feature column and y = label column
# one dataset is reprent of another dataset ie.
#x2 = 2 x1
#traing my model ke time pe it will start learning between the dataset itself 
# it will start adjusting the relationship between dataset itself
# which is wrng and we are suppoed to learn elationship between feature and label
# it will provide biases in coeffiecient parameters 
# there is no need to include two columns which provide th saame result

#Tv and radio/newspaper is not multicolinear
# -- complete random scatter graph

#do nt have multicolinarity in dataset -- checked 

#sales of ice cream in winter -- pearson r is -1 - negative correlate
#sales of umbrella in rainy season -- pearsons r is +1 - positive correlation
#sales f tv vs season -- not related 
#theres no missing values -- so we dont have to any imputation



In [ ]:
# pf is a pandas_profiling variable that is created
# to_widget comes under pandas_profiling library 
#u give the name test and make it into a file in html format
#creates dashboard ban gya

In [ ]:
pf.to_file("test.html") #saving this file for future purposes

In [ ]:
#build a model between  Tv and Sales
#feature vs label variable

In [ ]:
df

In [ ]:
x = df["TV"]
x

In [ ]:
y = df.Sales
y

In [ ]:
#Tv expenses varies with the sales data
#build a model -- find value of coefficient parameters ie. m and c 
# and update the values of m and c continuosly
#sales = mTv +c  -- y = mx +c
#there are 200 data pints it is not possible to calculate m and c and find contn
#continuosly for m and c so that it converges at a minima point

In [ ]:
#sklearn is a library jiske andar we have different models 


from sklearn.linear_model import LinearRegression

In [ ]:
import sklearn

In [ ]:
# LinearRegression class hai
#and linear is the object of that class 
linear =LinearRegression() # this is the object that we created of LinearRegression class
#class ke andar wale functions ko method bolte hai and you call those methods/functio
#inside a fit method, cmplete steps of training is written

In [ ]:
#fit is just a method that we can create 

linear.fit(x,y)

In [ ]:
X=df["TV"]
X
# df["TV"] is a series - dataframe ko series mein bolte hai 
#but linear.fit jo hain use 2d mein chiz chahiye ie. dataframe
#hence double bracket is needed
df[["TV","Sales"]]

In [ ]:
df.TV

In [ ]:
type(df["TV"])

In [ ]:
x= df[["TV"]]

In [ ]:
y = df[["Sales"]]

In [ ]:
#able t find value of m and c in fit 
# calculateeed value of m and c and changed the value f m and c by calci 
#de/dm and de/dc nd usme se changed value of m and c we found
#ives ptimal value f m and c
linear.fit(x,y)


In [ ]:
x= df[["TV"]]

In [ ]:
linear.fit(x,y)

In [ ]:
y = df.Sales
y

In [ ]:
linear.intercept_ #intercept is c 

In [ ]:
linear.coef_ # slope =m

In [ ]:
#sales = m TV +c 
#sales = 0.0475 TV + 7.03


In [ ]:
df["TV","Sales"] #this shows key error why??
# as there is nothing like 2-d series-- you need to use double brackets for 
# [[]] -- putting in a dataframe

In [ ]:
df

In [ ]:
df.Sales

In [ ]:
linear=LinearRegression()

In [ ]:
linear.fit(x,y)
#linear is the object we have trained with respect to x and y dataset
#this has m and c -- is object ke andar ye do values hai as it was saved
#and now i want to save this object inside a physical file -- share this file and pass data amd get result
#y=mx+c save hoga
#equation is changing -- x1,x2,and s on -- m1,m2,m3 --- the file size will also increase of
#file =linear_reg.sav -- is file ka size will increase -- this is a physical file

In [ ]:
linear.intercept_

In [ ]:
linear.coef_

In [ ]:
file = "linear_reg.sav" #just ek koi file banayi hai -- koibhinaam.sav
#you can even write file = "chinu.sav" -- chinu is just a random name and you save that in sav format

In [ ]:
file

In [ ]:
#pickle - seriasiable file format
# #Pickle is very useful for when you're working with machine learning algorithms, 
# where you want to save them to be able to make new predictions at a later time, without having to rewrite everything or 
# train the model all over again.
# open() is for opening the file for writing , open(filename(isko kuch bhi naam de sakte hai,"wb"(write mode be hoga))
                                                  

# pickle.dump(object you want to pickle,file to which the object has to be saved)
# ie. you'll pass yur object which is linear and save it in a file called linear_reg which will open in the write mode

In [ ]:
#saving the object -- value of m and c is there 
#we need to save this object inside a file -- s thats sharable

In [ ]:
pickle.dump(linear,open(file,"wb")) #wb is to write it #linear is an object of the class

In [ ]:
#prediction

In [ ]:
linear.predict([[45]]) #if on TV advertisement we spend 45$ then the sales would be 9.17

In [ ]:
linear.predict([[]])

In [ ]:
l= [4,5,3,2,23,44] #tv expenses
#Problem statement : tell me the sales on each and every expense of this

In [ ]:
for i in l:
    print(linear.predict([[i]]))

In [ ]:
#by default x input thats is feature input that scikit learn takes is a 2d input 

In [ ]:
#build a model ie some equation
#save that model - in a physical file 
#do the prediction of the model
#accuracy of the mdel using r^2

In [ ]:
saved_model=pickle.load(open(file,"rb"))

In [ ]:
saved_model

In [ ]:
saved_model.predict([[45]])

In [ ]:
#accurcy of the model

In [ ]:
linear.score(x,y) #accuracy is 61% -- R^2 (1-rss/tss) it lies between 0 and 1
#not a good score
#dataset is not showing a relationship 
#rss= summation(y-ypredict)^2
#tss = summation(y- ymean)^2

In [ ]:
#mutiple regression problem 
#https://archive.ics.uci.edu/ml/machine-learning-databases/00601/
# y = air temp
# x1,x2,x3= all rest of the columns 
# #load a data 
# profiling of data
# write your analysis/observation of data 
#go for imputation incase of nan
#if dataset not normal - handle it
#check multicolinearity
#build linear regresion model
#save it
#model accuarcy
#testcase
#all coding procedures to be followed


In [ ]:
df1 = pd.read_csv(r"C:\Users\acer\Desktop\New folder\Machine Learning Algorithms Lecture\ai4i2020.csv")

In [ ]:
df1

In [ ]:
df1.describe()

In [ ]:
pf= ProfileReport(df1)

In [ ]:
pf

In [ ]:
pf.to_widgets()

In [ ]:
linear1= LinearRegression()

In [ ]:
linear1

In [ ]:
x = df1["Process temperature [K]"]

In [ ]:
x=df1[["Process temperature [K]"]]

In [ ]:
y = df1["Air temperature [K]"]

In [ ]:
linear1.fit(x,y)

In [ ]:
linear1.coef_

In [ ]:
linear1.intercept_

In [ ]:
file = "linear_model.sav"

In [ ]:
pickle.dump(linear1,open(file,"wb"))

In [ ]:
saved_model1=pickle.load(open(file,"rb"))

In [ ]:
saved_model1.predict([[34]])

In [ ]:
########################## Linear Regression -2 ######################################################

In [ ]:
#multiple regression - multiple features and then build model
#Adjusted R^2
#Linear Regression is high bias, low variance model

#bias=error(y-ypredicted) or cost or loss functin
bias is a error that you get at the time of traini
#error more will adjust more and variance = dispersion of dataset
# whenver trying to model --


In [ ]:
df

In [ ]:
data_x = df[["TV","Radio","Newspaper"]]

In [ ]:
data_x

In [ ]:
y = df.Sales

In [ ]:
y

In [ ]:
df["TV"] #gives series

In [ ]:
df[["TV"]] #gives dataframe
#and can give multiple entries in this dataframe 


In [ ]:
lm = LinearRegression() #object of LinearRegression created -- LinearRegression is a class


In [ ]:
lm

In [ ]:
lm.fit(data_x,y) #this is going to build a linear regression model

In [ ]:
lm.intercept_

In [ ]:
lm.coef_

In [ ]:
lm.score(data_x,y)
#0.89 accuracy or R^2 hai- when considering ll 3 variables 
#confidence score hai yeh
#consider multiple column instead of one column 

In [ ]:
data2= df[["TV","Radio"]]

In [ ]:
y=df.Sales

In [ ]:
lm= LinearRegression()

In [ ]:
lm

In [ ]:
lm.fit(data2,y)

In [ ]:
lm.coef_

In [ ]:
lm.intercept_

In [ ]:
lm.score(data2,y) #approx same hai -- not much loss 

In [ ]:
-0.00103749

In [ ]:
#using statistical approach
#using statsistcal model

In [ ]:
import statsmodels.formula.api as smf
#ols = ordinary least square method

In [ ]:
lm= smf.ols(formula= "Sales ~ TV",data = df).fit()

In [ ]:
lm.summary()

In [ ]:
lm = smf.ols(formula="Sales ~ TV+Radio",data=df).fit()

In [ ]:
lm.summary()

In [ ]:
lm=smf.ols(formula="Sales ~ TV+Radio+Newspaper",data=df).fit()

In [ ]:
lm.summary()

In [ ]:
#mUlticolinarityy

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Ridge,Lasso,RidgeCV,LassoCV,ElasticNet,ElasticNetCV,LinearRegression #CV = Cross Validation
from sklearn.model_selection import train_test_split
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df=pd.read_csv("Admission_Prediction.csv") #admission_prediction dataset is saved in the folder hence no need to
#copy the entire path
#Build a model -- gre,teofl,uni ranking,sop,lor,cgpa,research -- what is the chance of admit?
#serial= index number 


In [3]:
df

Serial No.  GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  \
0             1      337.0        118.0                4.0  4.5  4.5  9.65   
1             2      324.0        107.0                4.0  4.0  4.5  8.87   
2             3        NaN        104.0                3.0  3.0  3.5  8.00   
3             4      322.0        110.0                3.0  3.5  2.5  8.67   
4             5      314.0        103.0                2.0  2.0  3.0  8.21   
..          ...        ...          ...                ...  ...  ...   ...   
495         496      332.0        108.0                5.0  4.5  4.0  9.02   
496         497      337.0        117.0                5.0  5.0  5.0  9.87   
497         498      330.0        120.0                5.0  4.5  5.0  9.56   
498         499      312.0        103.0                4.0  4.0  5.0  8.43   
499         500      327.0        113.0                4.0  4.5  4.5  9.04   

     Research  Chance of Admit  
0           1             0.92  
1           1             0.76  
2           1             0.72  
3           1             0.80  
4           0             0.65  
..        ...              ...  
495         1             0.87  
496         1             0.96  
497         1             0.93  
498         0             0.73  
499         0             0.84  

[500 rows x 9 columns]

In [ ]:
df.describe()

In [4]:
from pandas_profiling import ProfileReport

In [ ]:
pf=ProfileReport(df)

In [ ]:
pf.to_widgets()
#verify from thr grraph there exists a linear relaationship -- uske bad hi we can use linear regrssion 
#multicolinearity is there between features ad bhut blue hai
#missing data is also there 
#this data required preprocessing/improvements karni hai

In [ ]:
pf.to_file("Admission_Prediction_1.html")

In [ ]:
df

In [ ]:
#missing values are there in some features

In [5]:
df["GRE Score"] = df["GRE Score"].fillna(df["GRE Score"].mean())
#inplace=True not required as this is an reassignment operation
#pandas has something called fillna -- repplacing wherever you have na in the gre score column by its mean

In [ ]:
df["GRE Score"]

In [6]:
#fill all the null values which is inside toefl score by toefl score's mean 
df["TOEFL Score"]= df["TOEFL Score"].fillna(df["TOEFL Score"].mean())

In [7]:
df["University Rating"] = df["University Rating"].fillna(df["University Rating"].mean())

In [ ]:
 df.describe() #no missing values count has become 500 

In [8]:
df.isnull() #isnull gives true and false -- sab pandas ke andar ke function hai 


Serial No.  GRE Score  TOEFL Score  University Rating    SOP    LOR  \
0         False      False        False              False  False  False   
1         False      False        False              False  False  False   
2         False      False        False              False  False  False   
3         False      False        False              False  False  False   
4         False      False        False              False  False  False   
..          ...        ...          ...                ...    ...    ...   
495       False      False        False              False  False  False   
496       False      False        False              False  False  False   
497       False      False        False              False  False  False   
498       False      False        False              False  False  False   
499       False      False        False              False  False  False   

      CGPA  Research  Chance of Admit  
0    False     False            False  
1    False     False            False  
2    False     False            False  
3    False     False            False  
4    False     False            False  
..     ...       ...              ...  
495  False     False            False  
496  False     False            False  
497  False     False            False  
498  False     False            False  
499  False     False            False  

[500 rows x 9 columns]

In [9]:
df.isnull().sum() #no missing values

Serial No.           0
GRE Score            0
TOEFL Score          0
University Rating    0
SOP                  0
LOR                  0
CGPA                 0
Research             0
Chance of Admit      0
dtype: int64

In [ ]:
#seial number is a coolumn not of use -- drop it -- just indexing hai 

In [10]:
df.drop(columns = ["Serial No."],inplace = True)

In [ ]:
df

In [11]:
y= df["Chance of Admit"] #feature columnn
y

0      0.92
1      0.76
2      0.72
3      0.80
4      0.65
       ... 
495    0.87
496    0.96
497    0.93
498    0.73
499    0.84
Name: Chance of Admit, Length: 500, dtype: float64

In [12]:
x= df.drop(columns=["Chance of Admit"])
#reassignment operation to a variable x and hence inplace=True isnt used

In [ ]:
x

In [ ]:
#normalisation or standardisation lagana hai
#standard scalar is used for normalisation ie. z statistic

In [13]:
scaler= StandardScaler() #creating an object of standard scaler

In [14]:
arr = scaler.fit_transform(x) #trying to fit my features x are the features
#fit_transform is a function that is assciated with StandardScaler

In [ ]:
arr

In [15]:
#converting this array into dataframe
df1 =pd.DataFrame(arr)

In [ ]:
ProfileReport(df1)

In [16]:
pf2=df1.profile_report()

In [17]:
pf2.to_widgets()

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render widgets:   0%|          | 0/1 [00:00<?, ?it/s]

In [ ]:
df1 #variance of this dataset is not that high
#as it is ranging between a lower scale


In [ ]:
df1.describe()
#mean is close to 0 ie. e^-15
#std is close to 1 -- e^0 =1
#minimum maximum values is also not ranging ek dum upar niche 


In [ ]:
arr

In [18]:
#check multicolinarity using VIF - variance inflation factor 
#will calculate variance inflatin factor ie. VIF for each factor or dataset column
#variance_inflation_factor is a function here
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [ ]:
#idx== index
variance_inflation_factor()

In [ ]:
arr

In [ ]:
#500 records/rows in each column 
#number of columns =7
#for 7 columns we'll find the VIF
arr.shape

In [ ]:
arr.shape[0]

In [ ]:
arr.shape[1]

In [ ]:
range(7)

In [19]:
#it will iterate till 7 and give the VIF for each column 
for i in range(arr.shape[1]):
    print(variance_inflation_factor(arr,i))
    

4.153267572225826
3.792866110594647
2.508768242278763
2.7757495092534965
2.037307662489752
4.651669561154733
1.4593106786827288


In [20]:
# exog : an array containing features on which linear regression is performed.
# exog_idx : index of the additional feature whose influence on the other features is to be measured.
#calculationg VIF for each feature
vif_df[""[variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

SyntaxError: invalid syntax (<ipython-input-20-0c67d50754fe>, line 4)

In [22]:
#vif_df is an empty dataframe 
vif_df = pd.DataFrame()

In [23]:
#added one column vif in dataframe vif_df
vif_df["vif"] = [variance_inflation_factor(arr,i) for i in range(arr.shape[1])]

In [25]:
vif_df

vif           features
0  4.153268          GRE Score
1  3.792866        TOEFL Score
2  2.508768  University Rating
3  2.775750                SOP
4  2.037308                LOR
5  4.651670               CGPA
6  1.459311           Research

In [ ]:
#adding one more column in dataframe vif_df

In [ ]:
x

In [ ]:
type(x)

In [ ]:
x.columns

In [24]:
vif_df["features"] = x.columns

In [ ]:
vif_df
#vif score of each column is less than 10 -- not drop any column - not any dimension reduction technique
#use array as it is

In [ ]:
#split dataset into two different areas-- train and test split
#training data -- do training
#test-- verify


In [33]:
#arr is the dataset created after scaling our dataset -- applied normalisation
#85% of data for my training and 25% for my testing purpose
#arr is x- features ki values -- standardised wali
x_train,x_test,y_train, y_test = train_test_split(arr, y, test_size= 0.25)

In [34]:
x_train #dataset is changing -- it is splitting data in a random fashion 
#fixed random selection 

array([[ 1.21170361e+00,  1.45770580e+00,  1.66568791e+00, ...,
         1.09894429e+00,  1.29683885e+00,  8.86405260e-01],
       [ 4.00369625e-01,  2.99778313e-01,  7.78905651e-01, ...,
         5.58125251e-01,  9.16175040e-01,  8.86405260e-01],
       [-5.03714802e-02, -1.96476326e-01, -9.94658860e-01, ...,
         5.58125251e-01, -4.24423599e-01, -1.12815215e+00],
       ...,
       [ 4.90517846e-01,  4.65196526e-01, -1.07876604e-01, ...,
         1.73062093e-02, -9.54042814e-01, -1.12815215e+00],
       [ 3.10221404e-01,  4.65196526e-01,  1.66568791e+00, ...,
         1.63976333e+00,  1.03202924e+00,  8.86405260e-01],
       [-1.67303946e+00, -1.68524024e+00,  3.93810431e-16, ...,
        -5.23512832e-01, -2.26154025e+00, -1.12815215e+00]])

In [37]:
#if i give random_state= 345, the other person who has used the sme number the values will be exactly same 
#arr wo dataset hai features ka which is normalised/standardised
#y/label variable is not normalised as thats not required -- we wana keep that intact 
x_train,x_test,y_train,y_test = train_test_split(arr,y,test_size = 0.25, random_state = 345)

In [38]:
#us standardised array mein se hi split kiya hai data bas 
x_train #it is fixed now- fixed randomness

array([[-4.10964364e-01, -6.92730965e-01,  7.78905651e-01, ...,
         1.63976333e+00, -2.42366993e-01, -1.12815215e+00],
       [-1.67303946e+00, -1.02356739e+00,  7.78905651e-01, ...,
         1.09894429e+00, -1.46711143e+00,  8.86405260e-01],
       [-4.10964364e-01,  1.34360100e-01, -1.07876604e-01, ...,
        -5.23512832e-01, -7.68609886e-02, -1.12815215e+00],
       ...,
       [ 4.90517846e-01,  1.29228759e+00,  1.66568791e+00, ...,
         1.09894429e+00,  1.29683885e+00,  8.86405260e-01],
       [-1.67303946e+00, -1.68524024e+00,  3.93810431e-16, ...,
        -5.23512832e-01, -2.26154025e+00, -1.12815215e+00],
       [ 1.75259294e+00,  1.95396044e+00,  1.66568791e+00, ...,
         1.73062093e-02,  2.02506527e+00,  8.86405260e-01]])

In [39]:
lr = LinearRegression() #lr is a model

In [40]:
lr.fit(x_train,y_train)

LinearRegression()

In [41]:
import pickle

In [42]:
pickle.dump(lr, open("admission_lr_model.pickle", "wb")) #lr model we are supposed to dump
#pickle,sav format -- binary format or serialised file format 

In [ ]:
pickle.load(open("admission_lr_model","rb"))

In [46]:
ls

 Volume in drive C has no label.
 Volume Serial Number is 7AA3-19B5

 Directory of C:\Users\acer\Desktop\New folder\Machine Learning Algorithms Lecture

08/07/2022  09:38 PM    <DIR>          .
08/07/2022  09:38 PM    <DIR>          ..
08/07/2022  01:02 PM    <DIR>          .ipynb_checkpoints
08/07/2022  09:36 PM               560 admission_lr_model.pickle
08/07/2022  01:57 PM            16,085 Admission_Prediction.csv
08/07/2022  02:01 PM         4,646,143 Admission_Prediction_1.html
08/06/2022  07:34 PM           522,048 ai4i2020.csv
08/07/2022  09:38 PM            65,700 Linear Regression.ipynb
08/06/2022  09:11 PM               464 linear_model.sav
08/06/2022  07:01 PM               493 linear_reg.sav
08/07/2022  01:05 PM         1,265,057 test.html
               8 File(s)      6,516,550 bytes
               3 Dir(s)  10,261,266,432 bytes free


In [52]:
lr.predict([[337.000000,118.0,4.0,4.5,4.5,9.65,1]]) #score is 9.86\
#chance of admit is between 0 and 1 but this cmes at 9.86
#we have standardised our dataset ie. changed the whole range of the dataset
#is lr model mein standardised wale hi input karne hai -- na ki original values


array([9.86354874])

In [49]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [55]:
#scaler object that was created earlier for normalisation
#pass original data and it will normalise it 
test1 = scaler.transform([[337.000000,118.0,4.0,4.5,4.5,9.65,1]])

In [54]:
#prediction kar rhe hai from an object of linearRegression
lr.predict([[1.84274116, 1.78854223, 0.77890565, 1.13735981, 1.09894429,1.77680627, 0.88640526]])
#getting approx chance of admit close result 

array([0.95377928])

In [59]:
test2= scaler.transform([[324.000000,107.0,4.0,4.0,4.5,8.87,1]])

In [60]:
test2

array([[ 0.67081429, -0.03105811,  0.77890565,  0.63231549,  1.09894429,
         0.48585943,  0.88640526]])

In [62]:
lr.predict([[ 0.67081429, -0.03105811,  0.77890565,  0.63231549,  1.09894429,
         0.48585943,  0.88640526]])
#answer-- chance of admit is close to th expectation of 0.76

array([0.80990721])

In [68]:
#trying to read a physical file in my system 
#prediction kar rhe hai from a stored file 
model = pickle.load(open("admission_lr_model.pickle","rb"))

In [69]:
model.predict(test1)

array([0.95377928])

In [72]:
#not giving x_train and y_train coz these two datasets have already learned 
# now we should give an unknow dataset to check the real accuarcy which model has not seen yet
lr.score(x_test,y_test)
#r^2 

0.7476466381844958

In [ ]:
#we have created 25% of the dataset for testing purpose 
x_test

In [ ]:
y_test

In [80]:
#creating a function for adjusted R-squared
def adjR2(x,y):
    r2= lr.score(x,y)
    n=x.shape[0] #number of rows/records in dataset
    p=x.shape[1] #number of features/predictors
    adjusted_r2 = 1-((1-r2)*(n-1)/(n-p-1))
    return(adjusted_r2)
    
    #The value that is returned by a function  used as an argument passed to another function, 
    #stored as a variable, or just printed for the benefit of the human user.


In [74]:
#shape is in case of numpy-- array ke sath mein
x_test.shape[0] #no. of rows in this array

125

In [75]:
x_test.shape[1] #no. of columns in this array

7

In [81]:
adjR2(x_test,y_test) #actual accuarxy - 73.25%

0.7325485738023716

In [92]:
#to increase the accuarcy change the random_state
#see this order -- it will be x_train,x_test and then y_train, y_test
# x_train and x_test needs to be in array and y_train and y_test would be in series -- 
#x_train,y_train,x_test,y_test = train_test_split(arr,y, test_size = 0.25, random_state= 100)

x_train,x_test,y_train,y_test= train_test_split(arr,y,test_size=0.25,random_state=100)

In [93]:
x_train

array([[-0.41096436, -0.52731275, -0.1078766 , ...,  0.01730621,
        -0.25891759, -1.12815215],
       [ 0.12992496, -0.19647633, -0.1078766 , ..., -0.52351283,
         0.12174622, -1.12815215],
       [-1.13215013, -1.02356739, -0.99465886, ..., -1.06433187,
        -1.51676323, -1.12815215],
       ...,
       [-1.04200191, -0.85814918, -0.99465886, ..., -1.06433187,
        -0.65613201, -1.12815215],
       [-0.50111259, -0.85814918, -0.1078766 , ...,  0.55812525,
         0.10519562,  0.88640526],
       [-1.31244657, -0.85814918, -1.88144112, ..., -2.14596996,
        -0.95404281, -1.12815215]])

In [86]:
df

GRE Score  TOEFL Score  University Rating  SOP  LOR  CGPA  Research  \
0    337.000000        118.0                4.0  4.5  4.5  9.65         1   
1    324.000000        107.0                4.0  4.0  4.5  8.87         1   
2    316.558763        104.0                3.0  3.0  3.5  8.00         1   
3    322.000000        110.0                3.0  3.5  2.5  8.67         1   
4    314.000000        103.0                2.0  2.0  3.0  8.21         0   
..          ...          ...                ...  ...  ...   ...       ...   
495  332.000000        108.0                5.0  4.5  4.0  9.02         1   
496  337.000000        117.0                5.0  5.0  5.0  9.87         1   
497  330.000000        120.0                5.0  4.5  5.0  9.56         1   
498  312.000000        103.0                4.0  4.0  5.0  8.43         0   
499  327.000000        113.0                4.0  4.5  4.5  9.04         0   

     Chance of Admit  
0               0.92  
1               0.76  
2               0.72  
3               0.80  
4               0.65  
..               ...  
495             0.87  
496             0.96  
497             0.93  
498             0.73  
499             0.84  

[500 rows x 8 columns]

In [94]:
test3= scaler.transform([[337.000000,118.0,4.0,4.5,4.5,9.65,1]])

In [95]:
test3

array([[1.84274116, 1.78854223, 0.77890565, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

In [96]:
lr.predict([[1.84274116, 1.78854223, 0.77890565, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

array([0.95377928])

In [98]:
lr.score(x_test,y_test) #here it expects x input to be in 2d, whereas y input can be in series

0.831886769147379

In [101]:
#adjusted r2 is a better metric than r2 and here its value is slightly less than r2 value
#true score which is adjusted r2
adjR2(x_test,y_test)

0.8218287126006409

In [ ]:
######changing the test_size and then checking the accuracy############

In [102]:
x_train,x_test,y_train,y_test= train_test_split(arr,y,test_size = 0.15,random_state=100)

In [103]:
test5= scaler.transform([[337.000000,118.0,4.0,4.5,4.5,9.65,1]])

In [104]:
test5

array([[1.84274116, 1.78854223, 0.77890565, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

In [106]:
lr.predict([[1.84274116, 1.78854223, 0.77890565, 1.13735981, 1.09894429,
        1.77680627, 0.88640526]])

array([0.95377928])

In [107]:
lr.score(x_test,y_test)

0.846485169882467

In [108]:
adjR2(x_test,y_test)

0.8304463070343666

In [109]:
#equation of the model
lr.coef_ #m

array([0.02006269, 0.01295679, 0.00978097, 0.00451013, 0.01626859,
       0.07320679, 0.01332327])

In [110]:
lr.intercept_ #c

0.7211247125498041

In [ ]:
#linear regression model hai 
#nt using plane simple linear regression
#using simple linear regression+lasso

In [135]:
#normalising the dataset even tho it is normalised but just for the additionl effect --
#maximum iteration s= 2 lakh
#CV = cross validatio  -- tecnhnique used to find best possinle parameter 
#cv=10 -- diving the dataset into 10 chunks 
#49 datasets it is taking for training purpose and 1 dataset for testing purpose in random fashion
#finding hyperparameter for our model 

# https://www.kirenz.com/post/2019-08-12-python-lasso-regression-auto/

In [153]:
#Lasso with optimal alpha 
#Best model is selected by cross-validation used for hyper-tuning
model = LassoCV(alphas=None, cv=50,max_iter=2000000,normalize=True)

In [155]:
#Lasso Regression is an extension of linear regression that adds a 
#regularization penalty to the loss function during training

#Fit the model 
model.fit(x_train,y_train)

LassoCV(cv=50, max_iter=2000000, normalize=True)

In [157]:
#shows best value of penalisation chosen by cross validation
#finding the parameter
model.alpha_

3.65639233366671e-05

In [159]:
#best model -- use best value for our final model -- best value is the one
#we got after cross validation
lasso_best = Lasso(alpha= model.alpha_)
lasso_best

Lasso(alpha=3.65639233366671e-05)

In [160]:
#lasso model we are using -- instead of simple linear regression model
lasso_best.fit(x_train,y_train)

Lasso(alpha=3.65639233366671e-05)

In [162]:
#accuaracy -- it is found using test data - the unknow data 
lasso_best.score(x_test,y_test)

0.8421103469011295

In [ ]:
###############RIDGE REGRESSION##################

In [163]:
from sklearn.linear_model import RidgeCV

In [168]:
#select alpha frm these given numbers 
#alpha and lambda are same 

ridgecv =RidgeCV(alphas=(0.1,1.0,10.0), cv=10,normalize=True)#ridgecv object we created
ridgecv

RidgeCV(alphas=array([ 0.1,  1. , 10. ]), cv=10, normalize=True)

In [171]:
#give higher range - hyper parameter - give high range value of alpha
#using numpy libray generate 50 numbers between 0 to 10

np.random.uniform(0,10,50)

array([1.20204041, 9.73344066, 3.18844593, 2.49785385, 5.61548177,
       7.02135109, 8.66232484, 7.62776907, 9.43096903, 2.21268134,
       9.18733813, 6.80100597, 4.30479414, 9.61344811, 6.59139058,
       3.13568602, 7.14877033, 4.10387476, 8.10824438, 4.94487349,
       4.05258456, 2.99111311, 7.55508134, 4.41325668, 4.67239958,
       7.5594733 , 0.9214254 , 8.14373367, 7.10269001, 6.43057921,
       3.49167458, 3.40236389, 8.13253039, 5.68134528, 4.51263047,
       4.30348278, 5.59117104, 0.78799402, 4.95140278, 3.74973561,
       9.66062306, 7.44577092, 1.78517294, 1.02810652, 0.78449356,
       2.46124128, 7.73310521, 0.34373145, 7.5599669 , 4.60718521])

In [172]:
ridgecv = RidgeCV(alphas= np.random.uniform(0,10,50),cv=10,normalize= True)

In [173]:
ridgecv

RidgeCV(alphas=array([5.49016077e+00, 5.41467169e+00, 9.23812435e+00, 6.53644362e+00,
       8.96408702e+00, 8.40739254e-03, 3.23513866e+00, 5.98217326e+00,
       7.29234498e+00, 5.51142749e+00, 2.24793061e+00, 3.33160154e+00,
       9.56784882e+00, 5.92625297e+00, 4.59130468e+00, 6.43660879e+00,
       3.98363288e+00, 4.38666737e+00, 9.83276622e+00, 9.43589781e+00,
       2.82991444e+00, 4.48898536e+0...
       7.65815351e+00, 6.92209934e+00, 4.79857139e-01, 6.51067112e+00,
       3.59638557e+00, 4.70389623e+00, 8.97458300e+00, 9.34182752e+00,
       1.74639106e+00, 6.54674637e+00, 2.02945628e+00, 4.47207910e+00,
       8.36562768e+00, 7.39975423e+00, 1.31851381e+00, 2.76950725e+00,
       3.86896659e+00, 3.22895282e+00, 7.62328864e+00, 7.24154845e+00,
       8.50297252e+00, 3.18828771e+00]),
        cv=10, normalize=True)

In [174]:
ridgecv.fit(x_train,y_train)

RidgeCV(alphas=array([5.49016077e+00, 5.41467169e+00, 9.23812435e+00, 6.53644362e+00,
       8.96408702e+00, 8.40739254e-03, 3.23513866e+00, 5.98217326e+00,
       7.29234498e+00, 5.51142749e+00, 2.24793061e+00, 3.33160154e+00,
       9.56784882e+00, 5.92625297e+00, 4.59130468e+00, 6.43660879e+00,
       3.98363288e+00, 4.38666737e+00, 9.83276622e+00, 9.43589781e+00,
       2.82991444e+00, 4.48898536e+0...
       7.65815351e+00, 6.92209934e+00, 4.79857139e-01, 6.51067112e+00,
       3.59638557e+00, 4.70389623e+00, 8.97458300e+00, 9.34182752e+00,
       1.74639106e+00, 6.54674637e+00, 2.02945628e+00, 4.47207910e+00,
       8.36562768e+00, 7.39975423e+00, 1.31851381e+00, 2.76950725e+00,
       3.86896659e+00, 3.22895282e+00, 7.62328864e+00, 7.24154845e+00,
       8.50297252e+00, 3.18828771e+00]),
        cv=10, normalize=True)

In [175]:
ridgecv.alpha_

0.008407392537023162

In [176]:
Ridge_lr=Ridge(alpha=ridgecv.alpha_)

In [177]:
Ridge_lr.fit(x_train,y_train)

Ridge(alpha=0.008407392537023162)

In [178]:
Ridge_lr.score(x_test,y_test)

0.8420041002928649

In [ ]:
#ElasticNet

In [179]:
elastic= ElasticNetCV(alphas=None,cv=10)

In [180]:
elastic.fit(x_train,y_train)

ElasticNetCV(cv=10)

In [ ]:
#elastic formula needs alpha and lambda booth

In [181]:
elastic.alpha_ #lamba(theory pe  )

0.001391101145529104

In [182]:
elastic.l1_ratio_ #effect of l1- lasso-- theory wala alpha

0.5

In [184]:
elastic_lr=ElasticNet(alpha=elastic.alpha_,l1_ratio= elastic.l1_ratio_)

In [185]:
elastic_lr.fit(x_train,y_train)

ElasticNet(alpha=0.001391101145529104)

In [186]:
elastic_lr.score(x_test,y_test)

0.8419586493164081

In [ ]:
#ridge,lass,elasticnet-- gives almost accuarcy--
#as its is stable model-- not giving overfitted model
#max_iterations zadaa dena is helpful in large datasets, chote datasets mein computation power kharb karne wali baat hai

In [ ]:
#Assignment
#1.Deploy
#2. 